select * from customer limit 20
SELECT column_name 
FROM information_schema.columns
WHERE table_name = 'customer';

--Q1. What is the total revenue generated by male vs. female customers?
Select "Gender", SUM("Purchase Amount (USD)") as revenue
from customer
group by "Gender"


--Q2. Which customers used a discount but still spent more than the average purchase amount? 
Select "Customer ID", "Purchase Amount (USD)" 
From customer 
Where "Discount Applied" ='Yes' and "Purchase Amount (USD)" >= (select AVG("Purchase Amount (USD)") from customer)


-- Q3. Which are the top 5 products with the highest average review rating?
select "Item Purchased",round(avg("Review Rating"::numeric),2) as "Average Product Rating"
from customer
group by "Item Purchased"
order by avg("Review Rating") desc
limit 5

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select "Shipping Type", 
ROUND(AVG("Purchase Amount (USD)"),2)
from customer
where "Shipping Type" in ('Standard','Express')
group by "Shipping Type";

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
SELECT "Subscription Status",
       COUNT("Customer ID") AS "Total Customers",
       ROUND(AVG("Purchase Amount (USD)"),2) AS "Avg Spend",
       ROUND(SUM("Purchase Amount (USD)"),2) AS "Total Revenue"
FROM customer
GROUP BY "Subscription Status"
ORDER BY "Total Revenue","Avg Spend" DESC;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT "Item Purchased",
       ROUND(100.0 * SUM(CASE WHEN "Discount Applied" = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS "Discount Rate"
FROM customer
GROUP BY "Item Purchased"
ORDER BY "Discount Rate" DESC
LIMIT 5;


--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
with "Customer Type" as (
SELECT "Customer ID",
"Previous Purchases",
CASE 
    WHEN "Previous Purchases" = 1 THEN 'New'
    WHEN "Previous Purchases" BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS "Customer Segment"
FROM customer)

select "Customer Segment",count(*) AS "Number of Customers" 
from "Customer Type" 
group by "Customer Segment";

--Q8. What are the top 3 most purchased products within each category? 
WITH "Item Counts" AS (
    SELECT "Category",
           "Item Purchased",
           COUNT("Customer ID") AS "Total Orders",
           ROW_NUMBER() OVER (PARTITION BY "Category" ORDER BY COUNT("Customer ID") DESC) AS "Item Rank"
    FROM customer
    GROUP BY "Category", "Item Purchased"
)
SELECT "Item Rank","Category", "Item Purchased", "Total Orders"
FROM "Item Counts"
WHERE "Item Rank" <=3;
 
--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT "Subscription Status",
       COUNT("Customer ID") AS "Repeat Buyers"
FROM customer
WHERE "Previous Purchases" > 5
GROUP BY "Subscription Status";

--Q10. What is the revenue contribution of each age group? 
SELECT 
    "Age",
    SUM("Purchase Amount (USD)") AS total_revenue
FROM customer
GROUP BY "Age"
ORDER BY total_revenue desc;

